### ISSUE TITLE
Several initiatives present [CKAN / OKFN]

### ISSUE THREAD

**Issue by cafferata** [ckan/ckan-instances#117]
Hello,

I'm very curious why there are several iniatives from CKAN / OKFN for collecting CKAN / data portals right now? As far as I am familiar;
- https://github.com/okfn/dataportals.org/
- https://github.com/ckan/ckan-instances/

In addition, I see that other people have taken part in it;
- https://github.com/okfn/dataportals.org/issues/88 (@wfdd)

However, we had the same ideas from the Netherlands / data.overheid.nl, but before we started duplicating I was curious whether we could hook up to 1 central view. How do you see this? What, in your opinion, is a central place to discuss this?

Crosslinks:
- https://github.com/ckan/ckan-instances/issues/117
- https://github.com/okfn/dataportals.org/issues/132

**Comment by TkTech** [comment]
@cafferata the first one is an OKFN project that's platform agnostic, the second is *only* CKAN instances as it seems to power the "Used By" section of the site.
