### ISSUE TITLE
add uganda open data site

### ISSUE THREAD

**Issue by shevski** [ckan/ckan-instances#23]
URL: http://data.ug/
Type: Community
Where: Uganda
Description: A community led site aggregating public open data in Uganda, map layers and news. Built with CKAN, Drupal and Geonode.
Image: take the right size screenshot of: http://www.data.ug/

**Comment by johnmartin** [comment]
@shevski Shall I just add these without the description to start with?

**Comment by shevski** [comment]
The top one isn't finished yet and UG might not be maintained. I'm just using this as a reminder to find out, so no.

**Comment by nigelbabu** [comment]
@shevski Are these ready for adding? Can you please add the image the description?

**Comment by shevski** [comment]
Updated the description now! @johnmartin had a way to take the correct size screenshots before using some kind of program. Worth asking him what it was?

**Comment by johnmartin** [comment]
@nigelbabu @shevski This is what I used: https://gist.github.com/johnmartin/9327445
