### ISSUE TITLE
Display count at the top

### ISSUE THREAD

**Issue by shevski** [ckan/ckan-instances#4]
Showing how many instances are here for a particular filter, especially how many are in 'all'

should be '[x] CKAN instances' or similar

**Comment by johnmartin** [comment]
@shevski Done.

**Comment by shevski** [comment]
It just says "48 total instances" - number should change depending on filter and should not have the word "total" in it

**Comment by johnmartin** [comment]
Oh, I thought you wanted to show the total number... not the total for the individual facet. Are you sure? Because if that's the case when the page loads it'll only say: "3 featured instances", also any preference to 3 more CKAN instances that you want featured?

**Comment by johnmartin** [comment]
@shevski OK, how's this: http://instances.ckan.org/ ?

**Comment by shevski** [comment]
that's good
