### ISSUE TITLE
Italian National Open Data Portal

### ISSUE THREAD

**Issue by groundrace** [ckan/ckan-instances#53]
Name: dati.gov.it
Description: The Italian national open data portal.
URL: http://www.dati.gov.it/
Locale: Roma, IT
Type: National Government
Image:
![dati_gov_it](https://f.cloud.github.com/assets/3225570/1596662/3dde6b4a-5300-11e3-86dc-ed0de53bae50.png)

**Comment by mwainwright** [comment]
Duplicate
