### ISSUE TITLE
add http://dados.recife.pe.gov.br/dataset

### ISSUE THREAD

**Issue by shevski** [ckan/ckan-instances#54]
@mwainwright : can you add details for http://dados.recife.pe.gov.br/dataset ?

**Comment by mwainwright** [comment]
**Name** Dados Recife
**Description** Open data portal for the municipality of Recife, Brazil.
**URL** http://dados.recife.pe.gov.br/
**Locale** Recife, Brazil
**Type** Local govt

**Comment by shevski** [comment]
@mwainwright could you add some of the 'about' description here?

google translated it's:
"The Portal Open Data City Hall of Recife developed by EMPREL - Municipal Enterprise Computing , aims to provide the public and easily access and search data generated by government departments and agencies of municipal management. The publication of data in open format allows anyone to develop applications or views, seeking to facilitate data analysis, promoting the improvement of services through innovation and creativity, and contributing to greater participation in society by the municipal government."
