### ISSUE TITLE
Danish CKAN instances

### ISSUE THREAD

**Issue by autofunk** [ckan/ckan-instances#67]
City of Copenhagen open data portal - http://data.kk.dk/
City of Aarhus open data portal - http://www.odaa.dk/

**Comment by shevski** [comment]
@autofunk do you hve or could you provide descriptions of either? or ideally a pull request with all the info :)

**Comment by autofunk** [comment]
@shevski Pull request made :)

**Comment by nigelbabu** [comment]
Merged in @autofunk's pull request earlier.
